[2024-03-16 01:01:03,196] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: airflow_exam.retrieve_raw_data 2024-03-16T01:00:00+00:00 [queued]>
[2024-03-16 01:01:03,231] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: airflow_exam.retrieve_raw_data 2024-03-16T01:00:00+00:00 [queued]>
[2024-03-16 01:01:03,232] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-03-16 01:01:03,232] {taskinstance.py:1088} INFO - Starting attempt 1 of 6
[2024-03-16 01:01:03,232] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-03-16 01:01:03,246] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): retrieve_raw_data> on 2024-03-16T01:00:00+00:00
[2024-03-16 01:01:03,257] {standard_task_runner.py:52} INFO - Started process 108701 to run task
[2024-03-16 01:01:03,261] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', '***_exam', 'retrieve_raw_data', '2024-03-16T01:00:00+00:00', '--job-id', '5497', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpq1ngl_pk', '--error-file', '/tmp/tmpiruif9lq']
[2024-03-16 01:01:03,262] {standard_task_runner.py:77} INFO - Job 5497: Subtask retrieve_raw_data
[2024-03-16 01:01:03,344] {logging_mixin.py:104} INFO - Running <TaskInstance: ***_exam.retrieve_raw_data 2024-03-16T01:00:00+00:00 [running]> on host 3a3d0401ac26
[2024-03-16 01:01:03,464] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=***_exam
AIRFLOW_CTX_TASK_ID=retrieve_raw_data
AIRFLOW_CTX_EXECUTION_DATE=2024-03-16T01:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-16T01:00:00+00:00
[2024-03-16 01:01:03,987] {python.py:151} INFO - Done. Returned value was: None
[2024-03-16 01:01:04,006] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=***_exam, task_id=retrieve_raw_data, execution_date=20240316T010000, start_date=20240316T010103, end_date=20240316T010104
[2024-03-16 01:01:04,056] {taskinstance.py:1265} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2024-03-16 01:01:04,079] {local_task_job.py:151} INFO - Task exited with return code 0
